// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: message_template.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetTemplateIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorizerId uint32 `protobuf:"varint,1,opt,name=authorizer_id,json=authorizerId,proto3" json:"authorizer_id,omitempty"`
	TemplateName string `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
}

func (x *GetTemplateIdRequest) Reset() {
	*x = GetTemplateIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_template_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateIdRequest) ProtoMessage() {}

func (x *GetTemplateIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_template_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateIdRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateIdRequest) Descriptor() ([]byte, []int) {
	return file_message_template_proto_rawDescGZIP(), []int{0}
}

func (x *GetTemplateIdRequest) GetAuthorizerId() uint32 {
	if x != nil {
		return x.AuthorizerId
	}
	return 0
}

func (x *GetTemplateIdRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

type GetTemplateIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
}

func (x *GetTemplateIdResponse) Reset() {
	*x = GetTemplateIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_template_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateIdResponse) ProtoMessage() {}

func (x *GetTemplateIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_template_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateIdResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateIdResponse) Descriptor() ([]byte, []int) {
	return file_message_template_proto_rawDescGZIP(), []int{1}
}

func (x *GetTemplateIdResponse) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type TemplateItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateName string `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateId   string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
}

func (x *TemplateItem) Reset() {
	*x = TemplateItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_template_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateItem) ProtoMessage() {}

func (x *TemplateItem) ProtoReflect() protoreflect.Message {
	mi := &file_message_template_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateItem.ProtoReflect.Descriptor instead.
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return file_message_template_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateItem) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *TemplateItem) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetTemplateListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorizerId uint32 `protobuf:"varint,1,opt,name=authorizer_id,json=authorizerId,proto3" json:"authorizer_id,omitempty"`
}

func (x *GetTemplateListRequest) Reset() {
	*x = GetTemplateListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_template_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateListRequest) ProtoMessage() {}

func (x *GetTemplateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_template_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateListRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateListRequest) Descriptor() ([]byte, []int) {
	return file_message_template_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemplateListRequest) GetAuthorizerId() uint32 {
	if x != nil {
		return x.AuthorizerId
	}
	return 0
}

type GetTemplateListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*TemplateItem `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GetTemplateListResponse) Reset() {
	*x = GetTemplateListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_template_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateListResponse) ProtoMessage() {}

func (x *GetTemplateListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_template_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateListResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateListResponse) Descriptor() ([]byte, []int) {
	return file_message_template_proto_rawDescGZIP(), []int{4}
}

func (x *GetTemplateListResponse) GetResults() []*TemplateItem {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_message_template_proto protoreflect.FileDescriptor

var file_message_template_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x73, 0x67, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x60, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x22, 0x54, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0xca, 0x01, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x21,
	0x2e, 0x6d, 0x73, 0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x73, 0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x6d, 0x73, 0x67, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x6d, 0x73, 0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_template_proto_rawDescOnce sync.Once
	file_message_template_proto_rawDescData = file_message_template_proto_rawDesc
)

func file_message_template_proto_rawDescGZIP() []byte {
	file_message_template_proto_rawDescOnce.Do(func() {
		file_message_template_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_template_proto_rawDescData)
	})
	return file_message_template_proto_rawDescData
}

var file_message_template_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_template_proto_goTypes = []interface{}{
	(*GetTemplateIdRequest)(nil),    // 0: msgtemplate.GetTemplateIdRequest
	(*GetTemplateIdResponse)(nil),   // 1: msgtemplate.GetTemplateIdResponse
	(*TemplateItem)(nil),            // 2: msgtemplate.TemplateItem
	(*GetTemplateListRequest)(nil),  // 3: msgtemplate.GetTemplateListRequest
	(*GetTemplateListResponse)(nil), // 4: msgtemplate.GetTemplateListResponse
}
var file_message_template_proto_depIdxs = []int32{
	2, // 0: msgtemplate.GetTemplateListResponse.results:type_name -> msgtemplate.TemplateItem
	0, // 1: msgtemplate.MsgTemplateService.GetTemplateId:input_type -> msgtemplate.GetTemplateIdRequest
	3, // 2: msgtemplate.MsgTemplateService.GetTemplateList:input_type -> msgtemplate.GetTemplateListRequest
	1, // 3: msgtemplate.MsgTemplateService.GetTemplateId:output_type -> msgtemplate.GetTemplateIdResponse
	4, // 4: msgtemplate.MsgTemplateService.GetTemplateList:output_type -> msgtemplate.GetTemplateListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_template_proto_init() }
func file_message_template_proto_init() {
	if File_message_template_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_template_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_template_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_template_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_template_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_template_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_template_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_template_proto_goTypes,
		DependencyIndexes: file_message_template_proto_depIdxs,
		MessageInfos:      file_message_template_proto_msgTypes,
	}.Build()
	File_message_template_proto = out.File
	file_message_template_proto_rawDesc = nil
	file_message_template_proto_goTypes = nil
	file_message_template_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MsgTemplateServiceClient is the client API for MsgTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgTemplateServiceClient interface {
	GetTemplateId(ctx context.Context, in *GetTemplateIdRequest, opts ...grpc.CallOption) (*GetTemplateIdResponse, error)
	GetTemplateList(ctx context.Context, in *GetTemplateListRequest, opts ...grpc.CallOption) (*GetTemplateListResponse, error)
}

type msgTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgTemplateServiceClient(cc grpc.ClientConnInterface) MsgTemplateServiceClient {
	return &msgTemplateServiceClient{cc}
}

func (c *msgTemplateServiceClient) GetTemplateId(ctx context.Context, in *GetTemplateIdRequest, opts ...grpc.CallOption) (*GetTemplateIdResponse, error) {
	out := new(GetTemplateIdResponse)
	err := c.cc.Invoke(ctx, "/msgtemplate.MsgTemplateService/GetTemplateId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgTemplateServiceClient) GetTemplateList(ctx context.Context, in *GetTemplateListRequest, opts ...grpc.CallOption) (*GetTemplateListResponse, error) {
	out := new(GetTemplateListResponse)
	err := c.cc.Invoke(ctx, "/msgtemplate.MsgTemplateService/GetTemplateList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgTemplateServiceServer is the server API for MsgTemplateService service.
type MsgTemplateServiceServer interface {
	GetTemplateId(context.Context, *GetTemplateIdRequest) (*GetTemplateIdResponse, error)
	GetTemplateList(context.Context, *GetTemplateListRequest) (*GetTemplateListResponse, error)
}

// UnimplementedMsgTemplateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgTemplateServiceServer struct {
}

func (*UnimplementedMsgTemplateServiceServer) GetTemplateId(context.Context, *GetTemplateIdRequest) (*GetTemplateIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateId not implemented")
}
func (*UnimplementedMsgTemplateServiceServer) GetTemplateList(context.Context, *GetTemplateListRequest) (*GetTemplateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateList not implemented")
}

func RegisterMsgTemplateServiceServer(s *grpc.Server, srv MsgTemplateServiceServer) {
	s.RegisterService(&_MsgTemplateService_serviceDesc, srv)
}

func _MsgTemplateService_GetTemplateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgTemplateServiceServer).GetTemplateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgtemplate.MsgTemplateService/GetTemplateId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgTemplateServiceServer).GetTemplateId(ctx, req.(*GetTemplateIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgTemplateService_GetTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgTemplateServiceServer).GetTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgtemplate.MsgTemplateService/GetTemplateList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgTemplateServiceServer).GetTemplateList(ctx, req.(*GetTemplateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgTemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msgtemplate.MsgTemplateService",
	HandlerType: (*MsgTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTemplateId",
			Handler:    _MsgTemplateService_GetTemplateId_Handler,
		},
		{
			MethodName: "GetTemplateList",
			Handler:    _MsgTemplateService_GetTemplateList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_template.proto",
}
