// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: user_device.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type YN int32

const (
	YN_N YN = 0
	YN_Y YN = 1
)

// Enum value maps for YN.
var (
	YN_name = map[int32]string{
		0: "N",
		1: "Y",
	}
	YN_value = map[string]int32{
		"N": 0,
		"Y": 1,
	}
)

func (x YN) Enum() *YN {
	p := new(YN)
	*p = x
	return p
}

func (x YN) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YN) Descriptor() protoreflect.EnumDescriptor {
	return file_user_device_proto_enumTypes[0].Descriptor()
}

func (YN) Type() protoreflect.EnumType {
	return &file_user_device_proto_enumTypes[0]
}

func (x YN) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YN.Descriptor instead.
func (YN) EnumDescriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Item `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetResult() *Item {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetUserByDeviceIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId uint64 `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
}

func (x *GetUserByDeviceIdRequest) Reset() {
	*x = GetUserByDeviceIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByDeviceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByDeviceIdRequest) ProtoMessage() {}

func (x *GetUserByDeviceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByDeviceIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByDeviceIdRequest) Descriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByDeviceIdRequest) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type GetUserByDeviceIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Item `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GetUserByDeviceIdResponse) Reset() {
	*x = GetUserByDeviceIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByDeviceIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByDeviceIdResponse) ProtoMessage() {}

func (x *GetUserByDeviceIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByDeviceIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByDeviceIdResponse) Descriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByDeviceIdResponse) GetResults() []*Item {
	if x != nil {
		return x.Results
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt    string `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt    string `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Userid       uint64 `protobuf:"varint,4,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Openid       string `protobuf:"bytes,5,opt,name=Openid,proto3" json:"Openid,omitempty"`
	Title        string `protobuf:"bytes,6,opt,name=Title,proto3" json:"Title,omitempty"`
	DeviceId     uint64 `protobuf:"varint,7,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	DeviceNumber string `protobuf:"bytes,8,opt,name=DeviceNumber,proto3" json:"DeviceNumber,omitempty"`
	DeviceType   uint32 `protobuf:"varint,9,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Founder      YN     `protobuf:"varint,10,opt,name=Founder,proto3,enum=app.YN" json:"Founder,omitempty"`
	AuthorizerId uint32 `protobuf:"varint,11,opt,name=AuthorizerId,proto3" json:"AuthorizerId,omitempty"`
	ProvinceCode string `protobuf:"bytes,12,opt,name=ProvinceCode,proto3" json:"ProvinceCode,omitempty"`
	CityCode     string `protobuf:"bytes,13,opt,name=CityCode,proto3" json:"CityCode,omitempty"`
	CityName     string `protobuf:"bytes,14,opt,name=CityName,proto3" json:"CityName,omitempty"`
	AreaCode     string `protobuf:"bytes,15,opt,name=AreaCode,proto3" json:"AreaCode,omitempty"`
	AreaName     string `protobuf:"bytes,16,opt,name=AreaName,proto3" json:"AreaName,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_device_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_user_device_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Item) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Item) GetUserid() uint64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Item) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Item) GetDeviceNumber() string {
	if x != nil {
		return x.DeviceNumber
	}
	return ""
}

func (x *Item) GetDeviceType() uint32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *Item) GetFounder() YN {
	if x != nil {
		return x.Founder
	}
	return YN_N
}

func (x *Item) GetAuthorizerId() uint32 {
	if x != nil {
		return x.AuthorizerId
	}
	return 0
}

func (x *Item) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *Item) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *Item) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *Item) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *Item) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

var File_user_device_proto protoreflect.FileDescriptor

var file_user_device_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x70, 0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x36, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x22, 0x40, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0xd3, 0x03, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a,
	0x07, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x59, 0x4e, 0x52, 0x07, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x22, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x69, 0x74, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x41, 0x72, 0x65, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x41, 0x72, 0x65, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x12, 0x0a, 0x02, 0x59, 0x4e, 0x12, 0x05,
	0x0a, 0x01, 0x4e, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x59, 0x10, 0x01, 0x32, 0x91, 0x01, 0x0a,
	0x11, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x79, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_device_proto_rawDescOnce sync.Once
	file_user_device_proto_rawDescData = file_user_device_proto_rawDesc
)

func file_user_device_proto_rawDescGZIP() []byte {
	file_user_device_proto_rawDescOnce.Do(func() {
		file_user_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_device_proto_rawDescData)
	})
	return file_user_device_proto_rawDescData
}

var file_user_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_device_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_device_proto_goTypes = []interface{}{
	(YN)(0),                           // 0: app.YN
	(*GetRequest)(nil),                // 1: app.GetRequest
	(*GetResponse)(nil),               // 2: app.GetResponse
	(*GetUserByDeviceIdRequest)(nil),  // 3: app.GetUserByDeviceIdRequest
	(*GetUserByDeviceIdResponse)(nil), // 4: app.GetUserByDeviceIdResponse
	(*Item)(nil),                      // 5: app.Item
}
var file_user_device_proto_depIdxs = []int32{
	5, // 0: app.GetResponse.result:type_name -> app.Item
	5, // 1: app.GetUserByDeviceIdResponse.results:type_name -> app.Item
	0, // 2: app.Item.Founder:type_name -> app.YN
	1, // 3: app.UserDeviceService.Get:input_type -> app.GetRequest
	3, // 4: app.UserDeviceService.GetUserByDeviceId:input_type -> app.GetUserByDeviceIdRequest
	2, // 5: app.UserDeviceService.Get:output_type -> app.GetResponse
	4, // 6: app.UserDeviceService.GetUserByDeviceId:output_type -> app.GetUserByDeviceIdResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_device_proto_init() }
func file_user_device_proto_init() {
	if File_user_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByDeviceIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByDeviceIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_device_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_device_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_device_proto_goTypes,
		DependencyIndexes: file_user_device_proto_depIdxs,
		EnumInfos:         file_user_device_proto_enumTypes,
		MessageInfos:      file_user_device_proto_msgTypes,
	}.Build()
	File_user_device_proto = out.File
	file_user_device_proto_rawDesc = nil
	file_user_device_proto_goTypes = nil
	file_user_device_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserDeviceServiceClient is the client API for UserDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDeviceServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetUserByDeviceId(ctx context.Context, in *GetUserByDeviceIdRequest, opts ...grpc.CallOption) (*GetUserByDeviceIdResponse, error)
}

type userDeviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDeviceServiceClient(cc grpc.ClientConnInterface) UserDeviceServiceClient {
	return &userDeviceServiceClient{cc}
}

func (c *userDeviceServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/app.UserDeviceService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDeviceServiceClient) GetUserByDeviceId(ctx context.Context, in *GetUserByDeviceIdRequest, opts ...grpc.CallOption) (*GetUserByDeviceIdResponse, error) {
	out := new(GetUserByDeviceIdResponse)
	err := c.cc.Invoke(ctx, "/app.UserDeviceService/GetUserByDeviceId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDeviceServiceServer is the server API for UserDeviceService service.
type UserDeviceServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetUserByDeviceId(context.Context, *GetUserByDeviceIdRequest) (*GetUserByDeviceIdResponse, error)
}

// UnimplementedUserDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserDeviceServiceServer struct {
}

func (*UnimplementedUserDeviceServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserDeviceServiceServer) GetUserByDeviceId(context.Context, *GetUserByDeviceIdRequest) (*GetUserByDeviceIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByDeviceId not implemented")
}

func RegisterUserDeviceServiceServer(s *grpc.Server, srv UserDeviceServiceServer) {
	s.RegisterService(&_UserDeviceService_serviceDesc, srv)
}

func _UserDeviceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeviceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserDeviceService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeviceServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDeviceService_GetUserByDeviceId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByDeviceIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeviceServiceServer).GetUserByDeviceId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserDeviceService/GetUserByDeviceId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeviceServiceServer).GetUserByDeviceId(ctx, req.(*GetUserByDeviceIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.UserDeviceService",
	HandlerType: (*UserDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserDeviceService_Get_Handler,
		},
		{
			MethodName: "GetUserByDeviceId",
			Handler:    _UserDeviceService_GetUserByDeviceId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_device.proto",
}
