// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: internal/proto/wechat_push.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WechatPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonstr string `protobuf:"bytes,1,opt,name=jsonstr,proto3" json:"jsonstr,omitempty"`
}

func (x *WechatPushRequest) Reset() {
	*x = WechatPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wechat_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatPushRequest) ProtoMessage() {}

func (x *WechatPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wechat_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatPushRequest.ProtoReflect.Descriptor instead.
func (*WechatPushRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wechat_push_proto_rawDescGZIP(), []int{0}
}

func (x *WechatPushRequest) GetJsonstr() string {
	if x != nil {
		return x.Jsonstr
	}
	return ""
}

type WechatPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret string `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *WechatPushResponse) Reset() {
	*x = WechatPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wechat_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatPushResponse) ProtoMessage() {}

func (x *WechatPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wechat_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatPushResponse.ProtoReflect.Descriptor instead.
func (*WechatPushResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wechat_push_proto_rawDescGZIP(), []int{1}
}

func (x *WechatPushResponse) GetRet() string {
	if x != nil {
		return x.Ret
	}
	return ""
}

var File_internal_proto_wechat_push_proto protoreflect.FileDescriptor

var file_internal_proto_wechat_push_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x70, 0x22, 0x2d, 0x0a, 0x11, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6a, 0x73, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a,
	0x73, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x22, 0x26, 0x0a, 0x12, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x74, 0x32, 0x4b,
	0x0a, 0x11, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e,
	0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_wechat_push_proto_rawDescOnce sync.Once
	file_internal_proto_wechat_push_proto_rawDescData = file_internal_proto_wechat_push_proto_rawDesc
)

func file_internal_proto_wechat_push_proto_rawDescGZIP() []byte {
	file_internal_proto_wechat_push_proto_rawDescOnce.Do(func() {
		file_internal_proto_wechat_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_wechat_push_proto_rawDescData)
	})
	return file_internal_proto_wechat_push_proto_rawDescData
}

var file_internal_proto_wechat_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_wechat_push_proto_goTypes = []interface{}{
	(*WechatPushRequest)(nil),  // 0: app.WechatPushRequest
	(*WechatPushResponse)(nil), // 1: app.WechatPushResponse
}
var file_internal_proto_wechat_push_proto_depIdxs = []int32{
	0, // 0: app.WechatPushService.Put:input_type -> app.WechatPushRequest
	1, // 1: app.WechatPushService.Put:output_type -> app.WechatPushResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_wechat_push_proto_init() }
func file_internal_proto_wechat_push_proto_init() {
	if File_internal_proto_wechat_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_wechat_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wechat_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_wechat_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_wechat_push_proto_goTypes,
		DependencyIndexes: file_internal_proto_wechat_push_proto_depIdxs,
		MessageInfos:      file_internal_proto_wechat_push_proto_msgTypes,
	}.Build()
	File_internal_proto_wechat_push_proto = out.File
	file_internal_proto_wechat_push_proto_rawDesc = nil
	file_internal_proto_wechat_push_proto_goTypes = nil
	file_internal_proto_wechat_push_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WechatPushServiceClient is the client API for WechatPushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WechatPushServiceClient interface {
	Put(ctx context.Context, in *WechatPushRequest, opts ...grpc.CallOption) (*WechatPushResponse, error)
}

type wechatPushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWechatPushServiceClient(cc grpc.ClientConnInterface) WechatPushServiceClient {
	return &wechatPushServiceClient{cc}
}

func (c *wechatPushServiceClient) Put(ctx context.Context, in *WechatPushRequest, opts ...grpc.CallOption) (*WechatPushResponse, error) {
	out := new(WechatPushResponse)
	err := c.cc.Invoke(ctx, "/app.WechatPushService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WechatPushServiceServer is the server API for WechatPushService service.
type WechatPushServiceServer interface {
	Put(context.Context, *WechatPushRequest) (*WechatPushResponse, error)
}

// UnimplementedWechatPushServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWechatPushServiceServer struct {
}

func (*UnimplementedWechatPushServiceServer) Put(context.Context, *WechatPushRequest) (*WechatPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}

func RegisterWechatPushServiceServer(s *grpc.Server, srv WechatPushServiceServer) {
	s.RegisterService(&_WechatPushService_serviceDesc, srv)
}

func _WechatPushService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatPushServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.WechatPushService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatPushServiceServer).Put(ctx, req.(*WechatPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WechatPushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.WechatPushService",
	HandlerType: (*WechatPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _WechatPushService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/wechat_push.proto",
}
